"""Add restaurant_id to restaurant_pizzas

Revision ID: 25c0aa5f7bee
Revises: 133c9fe0be3a
Create Date: 2026-02-22 08:39:04.135684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c0aa5f7bee'
down_revision = '133c9fe0be3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_pizzas', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.add_column('restaurant_pizzas', sa.Column('pizza_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'restaurant_pizzas', 'pizzas', ['pizza_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_pizzas', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_pizzas', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_pizzas', type_='foreignkey')
    op.drop_column('restaurant_pizzas', 'pizza_id')
    op.drop_column('restaurant_pizzas', 'restaurant_id')
    # ### end Alembic commands ###
